version: 8.4
risky: false
finder:
  exclude:
    - "vendor"
    - "tests/temp"
  name:
    - "*.php"
preset: psr12
enabled:
  - align_comments
  - alpha_ordered_imports
  - array_indentation
  - assign_null_coalescing_to_coalesce_equal
  - backtick_to_shell_exec
  - blank_line_before_break
  - blank_line_before_continue
  - blank_line_before_declare
  - blank_line_before_return
  - blank_line_before_throw
  - blank_line_before_try
  - cast_spaces
  - class_reference_name_casing
  - clean_namespace
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - const_separation
  - die_to_exit
  - empty_loop_body_semicolon
  - empty_loop_condition
  - escape_implicit_backslashes
  - explicit_indirect_variable
  - explicit_string_variable
  - group_import
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - integer_literal_case
  - linebreak_after_opening_tag
  - magic_constant_casing
  - magic_method_casing
  - method_chaining_indentation
  - method_separation
  - multiline_comment_opening_closing
  - native_function_casing
  - native_type_declaration_casing
  - no_alternative_syntax
  - no_binary_string
  - no_blank_lines_after_phpdoc
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_multiline_whitespace_around_double_arrow
  - no_multiple_statements_per_line
  - no_null_property_initialization
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_single_line_asterisk_comment
  - no_spaces_inside_offset
  - no_spaces_outside_offset
  - no_superfluous_elseif
  - no_superfluous_phpdoc_tags_strict
  - no_trailing_comma_in_singleline_arguments
  - no_trailing_comma_in_singleline_array
  - no_trailing_comma_in_singleline_array_destructuring
  - no_trailing_comma_in_singleline_group_import
  - no_unneeded_braces
  - no_unneeded_control_parentheses
  - no_unneeded_import_alias
  - no_unset_cast
  - no_unused_imports
  - no_unused_lambda_imports
  - no_useless_concat_operator
  - no_useless_else
  - no_useless_nullsafe_operator
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - normalize_index_brace
  - normalize_nullable_type_declaration
  - not_operator_with_successor_space
  - nullable_type_declarations
  - object_operator_without_whitespace
  - php_unit_fqcn_annotation
  - php_unit_test_class_requires_covers
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_inline_tag_normalizer
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_order
  - phpdoc_return_self_reference
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_singular_inheritdoc
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_trim_consecutive_blank_line_separation
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_types_order
  - phpdoc_var_order
  - phpdoc_var_without_name
  - post_increment
  - print_to_echo
  - property_separation
  - protected_to_private
  - return_assignment
  - self_static_accessor
  - semicolon_after_instruction
  - short_array_syntax
  - simple_to_complex_string_variable
  - simplified_if_return
  - single_line_comment_spacing
  - single_line_throw
  - single_quote
  - single_space_after_construct
  - space_after_semicolon
  - standardize_increment
  - standardize_not_equals
  - switch_continue_to_break
  - ternary_to_null_coalescing
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_equals
  - union_type_without_spaces
  - whitespace_after_comma_in_array
disabled:
  - psr12_single_import_per_statement